### ISSUE TITLE
font config patch causing issues with pyinstaller

### ISSUE THREAD

**Issue by davidh-ssec** [conda-forge/vispy-feedstock#6]
I use PyInstaller to build an application that depends on vispy. In past versions (custom conda package) of vispy I had no issues bundling it up. In the conda-forge package I have issues due to the fontconfig.py patch which forces the path to `libfontconfig.so`. PyInstaller is unable to identify this as a dependency automatically and the library ends up not getting loaded.

Does anyone remember why this fontconfig patch is needed in conda/conda-forge?

**Comment by kmuehlbauer** [comment]
Ping @hadim Sorry for bugging you, can you say something about the fontconfig patch in the recipe. I cherry picked it from your original recipe back then.

**Comment by kmuehlbauer** [comment]
@davidh-ssec This is the staged-recipe when I got vispy into conda-forge: https://github.com/conda-forge/staged-recipes/pull/4242

I tried first without the patch, but added it later, obviously because something failed.

**Comment by davidh-ssec** [comment]
Interesting. Good point. I'd still be interested in the reasoning.

**Comment by davidh-ssec** [comment]
Found this at the bottom of the first build log:
```
+ source /opt/conda/bin/activate /staged-recipes/build_artefacts/vispy_1508916613270/_t_env
+ /staged-recipes/build_artefacts/vispy_1508916613270/_t_env/bin/python -s /staged-recipes/build_artefacts/vispy_1508916613270/test_tmp/run_test.py
import: 'vispy'
Traceback (most recent call last):
  File "/staged-recipes/build_artefacts/vispy_1508916613270/test_tmp/run_test.py", line 2, in <module>
    import vispy
  File "/staged-recipes/build_artefacts/vispy_1508916613270/_t_env/lib/python2.7/site-packages/vispy/__init__.py", line 30, in <module>
    from .util import config, set_log_level, keys, sys_info  # noqa
  File "/staged-recipes/build_artefacts/vispy_1508916613270/_t_env/lib/python2.7/site-packages/vispy/util/__init__.py", line 14, in <module>
    from . import fonts       # noqa
  File "/staged-recipes/build_artefacts/vispy_1508916613270/_t_env/lib/python2.7/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
    from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
  File "/staged-recipes/build_artefacts/vispy_1508916613270/_t_env/lib/python2.7/site-packages/vispy/util/fonts/_triage.py", line 11, in <module>
    from ._freetype import _load_glyph
  File "/staged-recipes/build_artefacts/vispy_1508916613270/_t_env/lib/python2.7/site-packages/vispy/util/fonts/_freetype.py", line 16, in <module>
    from ...ext.fontconfig import find_font
  File "/staged-recipes/build_artefacts/vispy_1508916613270/_t_env/lib/python2.7/site-packages/vispy/ext/fontconfig.py", line 12, in <module>
    raise ImportError('fontconfig not found')
ImportError: fontconfig not found
TESTS FAILED: vispy-0.5.0-py27_0.tar.bz2
Exited with code 1
```
